"use client";
import React, { useEffect } from "react";
import { AuthProvider } from "./auth"; // Certifique-se de importar o AuthProvider corretamente
import localFont from "next/font/local";
import "./globals.css";
import { metadata } from "./metadata";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
    // ✅ Registra o Service Worker manualmente para funcionar com `next export`
    useEffect(() => {
      if ("serviceWorker" in navigator) {
        navigator.serviceWorker
          .register("/sw.js")
          .then(() => console.log("Service Worker registrado com sucesso!"))
          .catch((error) => console.error("Erro ao registrar Service Worker:", error));
      }
    }, []);
  return (
    <html lang="pt">
      <head>
      <title>{metadata.title?.toString() ?? "Vendas Mobile"}</title>
      <meta name="description" content={metadata.description?? "Generated by ASKSYSTEMS"} />

        {/* Ícone do App */}
        <link rel="icon" href="/icon-192x192.png" />

        {/* PWA Manifest */}
        <link rel="manifest" href="/manifest.json" />

        {/* Configuração de cor no navegador */}
        <meta name="theme-color" content="#4CAF50" />

        {/* Suporte a PWA em iOS */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="Vendas Mobile" />
        <link rel="apple-touch-icon" href="/icon-192x192.png" />

        {/* Fonte para ícones do Material Design */}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-cover bg-center min-h-screen`}
        style={{ backgroundImage: "url('/background.jpg')" }}
      >
        <div className="flex h-screen">
          <div id="__next" className="flex-1 bg-white bg-opacity-90 shadow-md rounded-lg p-6 m-4 overflow-y-auto">
            <AuthProvider>{children}</AuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
