//src/app/layout.tsx
import React from 'react';
import { AuthProvider } from './auth'; // Certifique-se de importar o AuthProvider corretamente
 import type { Metadata } from "next";
 import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "VENDAS MOBILE",
  description: "Generated by ASKSYSTEMS",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt">
      <head>
        {/* Inclui o link para os ícones do Material Design */}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      </head>      
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* O layout geral não precisa ter lógica de autenticação */}
        <div className="flex h-screen">
          <div  id="__next" className="flex-1 bg-gray-100  overflow-y-auto">
            <AuthProvider> {/* Envolva os componentes no AuthProvider */}
              {children}
            </AuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
